### PR TITLE
disable magclass_sizeLimit; doesn't matter whether preprocessing fails on OOM or OOMagclass

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**

### CODE REVIEW

**Review by LaviniaBaumstark — COMMENTED** [review]
do we really want to disable it completely?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Any point in keeping it around?

**Comment by LaviniaBaumstark** [comment]
we might spam the cluster with any size of magclass object...

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
How?

Scenario A – no change:
- preprocessing run fails on OOMagclass
- restarting the run w/o `magclass_sizeLimit`
- run might succeed or it might OOM
- so one possible OOM run on the cluster

Scenario B – permanently disabling `magclass_sizeLimit`
- run might succeed or it might OOM
- so one possible OOM run on the cluster

If anything we are saving one additional run per OOM run.

**Comment by fbenke-pik** [comment]
If I understand it correctly, we will always get OOMagclass once Robin introduces the new EDGEbuildings inputdata (as it is and without caching available) , unless we increase the magclass size limit permanently, right? 

So if we decide that Robin should work on keeping the size below this threshold by removing unnecessary data and are willing to enforce the same restriction to future data until it becomes absolutely impossible, then it might be worth keeping the size limit. If this is sth we turn off the moment it becomes uncomfortable, then we might as well get rid of it and merge this change.

**Review by LaviniaBaumstark — APPROVED** [review]

**Review by robinhasse — APPROVED** [review]
Makes sense to me. Thanks, Michaja. Of course I'll try to reduce the file size nonetheless.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Of course I'll try to reduce the file size nonetheless.

To wit: https://github.com/pik-piam/magclass/pull/140

**Pull request merged**
